layout_spectrum: 0.2319149
name: rqgenesis
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
navigation:
  - name: Mighty Audio's Portable Player
    id: e7eff245-5cae-4ea8-bfa2-a0108d5647d6
    type: content
    url: 2016-04-15-mighty-audios-portable-player.html
color:
  brandStrength: 0.4212766
  lightness: 0.2600549217313528
  saturation: 0.6346986165735871
  rhythmicContrast: 0.520179747371003
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
typography_spectrum: 0.1486601969227195
