typography_spectrum: 0.4553191
color:
  brandStrength: 0.4212766
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
layout_spectrum: 0
author:
  url: www.rqgenesis.com
  name: Jaroslav Dokoupil
  email: jaroslav@rqgenesis.com
name: RQ Genesis
navigation: []
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
title: Creating Sustainable Value
