typography_spectrum: 0.4553191
color:
  brandStrength: 0.4212766
  saturation: 1
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  lightness: 1
  rhythmicContrast: 1
layout_spectrum: 0
analytics:
  google: UA-44733812-3
author:
  url: ''
  name: ''
  email: ''
name: RQ GENESIS online
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
title: RQ GENESIS online
description: ''
