description: 'Innovation, Technology, Leadership, Culture, Strategy'
title: RQ online
navigation:
  - url: 'http://rqgenesis.com'
    name: RQ GENESIS
    type: external
layout_spectrum: 0.7638298
author:
  url: ''
  name: ''
  email: ''
name: RQ online
analytics:
  google: UA-44733812-3
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
color:
  brandStrength: 0.4212766
  saturation: 1
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  lightness: 1
  rhythmicContrast: 1
typography_spectrum: 0.4957447
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/6207061d-7257-4761-94e4-8f925d6d7571.png
