typography_spectrum: 0.4553191
color:
  brandStrength: 0.4212766
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
layout_spectrum: 0
author:
  url: ''
  name: ''
  email: ''
name: RQ Genesis
navigation:
  - name: WHY
    id: f2eb41af-4771-4c5b-92f1-502c21691885
    type: content
  - name: HOW
    id: 43af9c49-6c00-466c-9000-6d50b18955ff
    type: content
  - name: WHAT
    id: a27c2c26-d753-471f-96a2-89e204c84554
    type: content
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
title: RQ GENESIS
description: Creating Sustainable Value
