layout_spectrum: 0.2319149
name: rqgenesis
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
navigation: []
typography_spectrum: 0.9702128
color:
  brandStrength: 0.4212766
  saturation: 0.6346986165735871
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  lightness: 0.2600549217313528
  rhythmicContrast: 0.520179747371003
