typography_spectrum: 0.4553191
color:
  brandStrength: 0.4212766
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
layout_spectrum: 0
author:
  url: www.rqgenesis.com
  name: Jaroslav Dokoupil
  email: jaroslav@rqgenesis.com
name: RQ Genesis
navigation:
  - id: f2eb41af-4771-4c5b-92f1-502c21691885
    url: 2016-07-25-why.html
    name: WHY
    type: content
  - id: 43af9c49-6c00-466c-9000-6d50b18955ff
    url: 2016-07-25-how.html
    name: HOW
    type: content
  - id: a27c2c26-d753-471f-96a2-89e204c84554
    url: 2016-07-25-what.html
    name: WHAT
    type: content
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
title: Creating Sustainable Value
