layout_spectrum: 0.17613006476312876
typography_spectrum: 0.550209840061143
color:
  brandStrength: 0.4553191
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.5382979
  brandColors:
    - '#000000'
    - '#FFFFFF'
    - '#F3AB44'
    - '#848484'
    - '#D1D0D1'
description: 'Innovation, Technology, Leadership, Culture, Strategy'
title: RQ online
navigation:
  - url: 'http://rqgenesis.com'
    name: RQ GENESIS
    type: external
author:
  url: ''
  name: ''
  email: ''
name: RQ online
analytics:
  google: UA-44733812-3
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/6207061d-7257-4761-94e4-8f925d6d7571.png
